/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.freehep.connexion.jni;

public class Connexion {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Connexion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Connexion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ConnexionAdapterJNI.delete_Connexion(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Connexion() {
    this(ConnexionAdapterJNI.new_Connexion(), true);
  }

  public void setConnexionCallback(ConnexionCallback connexionCallback) {
    ConnexionAdapterJNI.Connexion_setConnexionCallback(swigCPtr, this, ConnexionCallback.getCPtr(connexionCallback), connexionCallback);
  }

  public static ConnexionCallback getCallback() {
    long cPtr = ConnexionAdapterJNI.Connexion_getCallback();
    return (cPtr == 0) ? null : new ConnexionCallback(cPtr, false);
  }

  public void run() {
    ConnexionAdapterJNI.Connexion_run(swigCPtr, this);
  }

}
