/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.freehep.connexion.jni;

class ConnexionAdapterJNI {
  public final static native long new_ConnexionCallback();
  public final static native void delete_ConnexionCallback(long jarg1);
  public final static native void ConnexionCallback_addDevice(long jarg1, ConnexionCallback jarg1_, int jarg2);
  public final static native void ConnexionCallback_addDeviceSwigExplicitConnexionCallback(long jarg1, ConnexionCallback jarg1_, int jarg2);
  public final static native void ConnexionCallback_removeDevice(long jarg1, ConnexionCallback jarg1_, int jarg2);
  public final static native void ConnexionCallback_removeDeviceSwigExplicitConnexionCallback(long jarg1, ConnexionCallback jarg1_, int jarg2);
  public final static native void ConnexionCallback_handleAxis(long jarg1, ConnexionCallback jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8);
  public final static native void ConnexionCallback_handleAxisSwigExplicitConnexionCallback(long jarg1, ConnexionCallback jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8);
  public final static native void ConnexionCallback_handleButtons(long jarg1, ConnexionCallback jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native void ConnexionCallback_handleButtonsSwigExplicitConnexionCallback(long jarg1, ConnexionCallback jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native void ConnexionCallback_director_connect(ConnexionCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ConnexionCallback_change_ownership(ConnexionCallback obj, long cptr, boolean take_or_release);
  public final static native int CONNEXION_H_get();
  public final static native long new_Connexion();
  public final static native void delete_Connexion(long jarg1);
  public final static native void Connexion_setConnexionCallback(long jarg1, Connexion jarg1_, long jarg2, ConnexionCallback jarg2_);
  public final static native long Connexion_getCallback();
  public final static native void Connexion_run(long jarg1, Connexion jarg1_);

    static {
        String libName = "freehep-connexion"+"-"+"1.0-SNAPSHOT";
        try {
            System.err.print("Loading JNI Library: "+libName+"...");
            System.loadLibrary(libName);
            System.err.println("OK.");
        } catch (UnsatisfiedLinkError e) {
            System.err.println("\nJNI Library "+libName+" failed to load.\n" + e);
            System.exit(1);
        }
    }


  public static void SwigDirector_ConnexionCallback_addDevice(ConnexionCallback self, int device) {
    self.addDevice(device);
  }
  public static void SwigDirector_ConnexionCallback_removeDevice(ConnexionCallback self, int device) {
    self.removeDevice(device);
  }
  public static void SwigDirector_ConnexionCallback_handleAxis(ConnexionCallback self, int device, int x, int y, int z, int rx, int ry, int rz) {
    self.handleAxis(device, x, y, z, rx, ry, rz);
  }
  public static void SwigDirector_ConnexionCallback_handleButtons(ConnexionCallback self, int device, int value, int buttons) {
    self.handleButtons(device, value, buttons);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
