// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it.
// =========================================================================
#ifndef HEPREP_JHEPREPCONSTANTS_H
#define HEPREP_JHEPREPCONSTANTS_H 1

// Copyright 2000, FreeHEP.

#include <jni.h>

#include "HEPREP/HepRepConstants.h"

#include "JHepRepRef.hh"

/**
 *
 * @author M.Donszelmann
 * @author J.Perl
 *
 */
class JHepRepConstants: public JHepRepRef, public virtual HEPREP::HepRepConstants {

protected:
    inline JHepRepConstants() { };
    inline JHepRepConstants(const JHepRepConstants& r) { };
    inline JHepRepConstants& operator=(const JHepRepConstants&) { return *this; };

public:
    JNIEXPORT JHepRepConstants(HEPREP::HepRepFactory *f, jobject obj);

    /// Destructor.
    JNIEXPORT virtual ~JHepRepConstants();
}; // class

#endif /* ifndef HEPREP_JHEPREPCONSTANTS_H */
