// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it.
// =========================================================================

#include <cstdlib>
#include <iostream>

#include "HEPREP/HepRepFactory.h"

#include "JHepRepRef.hh"
#include "JHepRepConstants.hh"

using namespace HEPREP;

JNIEXPORT JHepRepConstants::JHepRepConstants(HepRepFactory *f, jobject obj)
        : JHepRepRef(f, obj) {

}

JNIEXPORT JHepRepConstants::~JHepRepConstants() {
}
